spring.application.name=backend

spring.datasource.url=jdbc:mysql://localhost:3306/smart_order_platform
spring.datasource.username=root
spring.datasource.password=Antshikha@2902

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true